rest/client.go
rest/routes.go
rest/service.go

JIRA: https://jira.mongodb.org/browse/MAKE-1172
* Add POST routes for login. The GET routes will be removed after people update their CLIs.
* Dont close request bodies. The docs say that the underlying http.Server is responsible for closing them so the `http.Handler` doesn't have to.

MAKE-1172: add POST routes for login

---

perf/change_point_detector.go
util/http.go

When the connection times out in Kanopy, no actual error is received by the client - only a nil body. This causes an EOF error.

MAKE-1151: Fix timeout issue coming from EOFs

---

benchmarks/log_iterator_benchmarks.go
benchmarks/timber_benchmarks.go

JIRA: https://jira.mongodb.org/browse/EVG-9709
`go build ./benchmarks` was failing.

EVG-9709: fix benchmarks compilation

---

model/buildlogger.go
model/buildlogger_test.go
model/log_iterator_test.go
rest/buildlogger_routes.go
rest/buildlogger_routes_test.go
rest/data/buildlogger.go
rest/data/buildlogger_test.go
rest/data/interface.go

These changes:
- Fix the model and rest code to filter execution correctly (if execution is not set, the latest execution is fetched).
- Adds testing for the above change.
- Cleans up some of the code.
[EVG-9700](https://jira.mongodb.org/browse/EVG-9700)

EVG-9700: Fix execution filtering and add testing for buildlogger

---

model/buildlogger.go
model/buildlogger_test.go
rest/buildlogger_routes.go
rest/buildlogger_routes_test.go
rest/data/buildlogger.go
rest/data/interface.go

This ticket is part of [EVG-9700](https://jira.mongodb.org/browse/EVG-9700). It corrects the filtering by "group", which is reality just a tag in the log metadata but needs to be filtered separately in cases where there is a group and tags as the `$in` filter in mongo returns an array with any of the matching fields (rather than all).

EVG-9700: Correctly filter groups

---

model/buildlogger.go
model/buildlogger_test.go

This is part of [EVG-9700](https://jira.mongodb.org/browse/EVG-9700).
This adds more robust testing for the buildlogger grouping functionality, specifically for grouped logs that have disjoint time ranges. The changes here also fix a bug where the sort field for execution was incorrect.

EVG-9700: Test Buildlogger grouping with disjoint times

---

makefile

JIRA: https://jira.mongodb.org/browse/EVG-12649
`make-tarball` will compile to the native GOOS so that it can run, but the cedar binary compiles to the target GOOS (if it's set).

EVG-12649: allow cross-compilation using GOOS

---

evergreen.yaml
operations/admin.go
rest/client.go
rest/routes.go
rest/service.go
rpc/internal/perf_service_test.go

JIRA: https://jira.mongodb.org/browse/EVG-9694
I'm going to migrate the settings off of LDAP and deploy after this is merged.
* Remove REST routes and REST client methods that auth to retrieve the API key.
* Remove debug logs for migration.
* Remove all places that give password as credentials to server except where necessary to use naive auth in tests. For production, we don't use naive auth so it doesn't matter.

EVG-9694: migrate off of LDAP

---

model/system_metrics.go
model/system_metrics_test.go
model/test_results.go
model/test_results_test.go

JIRA: https://jira.mongodb.org/browse/EVG-12752
This is the first of a series of tickets to add the rest route to fetch system metrics data. This ticket:
1.) Adds a `FindByTaskID` method on the `SystemMetrics` struct in the `model` package.
2.) Cleans up some tests and comments.

EVG-12752: Add FindByTaskID method to system metrics model

---

model/system_metrics.go
model/system_metrics_test.go
rest/service.go

JIRA: https://jira.mongodb.org/browse/EVG-12752
This PR simply changes the system metrics reader in the `model` package to a read closer; there is an edge case where some of the underlying `io.ReadCloser` objects returned from `pail` are not closed.

EVG-12752: System metrics reader should be a read closer

---

model/system_metrics.go
model/system_metrics_test.go
model/test_utils.go
rest/data/system_metrics.go

JIRA: https://jira.mongodb.org/browse/EVG-12820
This is the first of 2 PRs for this ticket. In this PR I changed the system metrics model code to have a separate `DownloadWithPagination` method and enabled a soft size limit in the `SystemMetricsReadCloser`.

EVG-12820: Add pagination to system metrics download

---

units/simple_log_save.go

JIRA: https://jira.mongodb.org/browse/EVG-9080
It seems like most of the URLs already use virtual hosted-style URLs except for this one. Virtual hosted-style URLs won't work well for bucket names with dots unless you use HTTP (which this URL does for some reason) or write your own SSL certificate verification.

EVG-9080: use virtual hosted-style S3 URLs

---

.golangci.yml
model/test_results.go
model/test_results_test.go
rest/data/interface.go
rest/data/test_results.go
rest/data/test_results_test.go
rest/test_results_routes_test.go

JIRA: https://jira.mongodb.org/browse/EVG-12996
The bucket used for the test result iterator should not include the test results collection name in the prefix. I also added a check for errors after calling `(*TestResultsIterator).Next()`.

EVG-12996: fix test results REST routes

---

cost/evg_client.go
cost/evg_client_test.go
cost/evg_distros.go
cost/evg_projects.go
model/config.go
model/config_flags.go
units/historical_stats.go

JIRA: https://jira.mongodb.org/browse/EVG-13127
* Add service user to Cedar global configuration to auth into Evergreen's REST API and get historical stats settings for the project.
* I'm going to add a service user in Evergreen with permission to read the project settings.
* Write stub of historical stats job that only gets project settings.

EVG-13127: add service user to get historical stats project settings

---

rpc/internal/perf_service_test.go
rpc/internal/test_results_service.go
rpc/internal/test_results_service_test.go

JIRA: https://jira.mongodb.org/browse/EVG-13132
The gRPC TestResult payload does not include the task ID and execution, so we have to pull this information from the DB's TestResults record to store it with the S3 test result.
I also added a flag like we use in Evergreen to skip integration tests, since they're difficult to test without CI.

EVG-13132: set task ID and execution number for test result

---

model/system_metrics.go
model/system_metrics_test.go

JIRA: https://jira.mongodb.org/browse/EVG-13051
The tests appear to be flaking because `(*model.SystemMetrics).Append()` relies on using unix timestamps in milliseconds for unique keys in the bucket. However, tests sometimes run fast enough that two calls to `Append()` occur within the same millisecond, which causes the earlier one to be overwritten.
The buildlogger tests that use `(*model.Log).Append()` also suffer from flakiness because they use sleeping and unix timestamps in milliseconds.
* Drop test collections during test setup.
* Use unix nanosecond timestamps instead of millisecond timestamps (while it's not perfect, it's highly unlikely that two `Append()` calls would occur in the same nanosecond).
* Remove reliance on sleeping in system metrics test.

EVG-13051: fix flaky system metrics tests

---

model/perf.go
model/perf_data.go
model/perf_data_test.go
model/perf_test.go

JIRA: https://jira.mongodb.org/browse/EVG-13301
There are two ways to add rollups: (1) via `PerformanceResult.SaveNew` and (2) via `PerformanceResult.MergeRollups`. The latter ensures no duplicate rollup names are added and checks against the version of a rollup (if it exists already). This PR refactors `PerformanceResult.SaveNew` to use `MergeRollups` instead of inserting the rollups as they are.

EVG-13301: Merge rollups when saving new perf data

---

rest/routes.go

JIRA: https://jira.mongodb.org/browse/EVG-12916
We shouldn't need these logs anymore, which were mostly used to identify users who were still relying on LDAP auth.

EVG-12916: remove transitional auth logs

---

perf/ftdc_rollups.go
perf/ftdc_rollups_test.go
perf/rollup_factory.go

JIRA: https://jira.mongodb.org/browse/EVG-13536
This adds two rollups based on `n` (number of documents) from the raw ftdc data, `DocumentThroughput` and `DocumentsTotal`.

EVG-13536: Add perf rollups based on counter.n

---

model/time_series_update.go
units/time_series_update_test.go

JIRA: https://jira.mongodb.org/browse/EVG-13431
This adds a `$sort` and `$group` stage to the aggregation pipeline when fetching performance data for signal processing. The `$sort` sorts by execution and the `$group` groups by `task_id` using the `$last` accumulator to get only the latest execution in each group.

EVG-13431: Only report latest execution when forwarding performance results from cedar into signal processing service

---

cedar.go
model/historical_test_data.go
model/historical_test_data_test.go
rest/data/historical_test_data.go
rest/data/historical_test_data_test.go
rest/data/impl.go
rest/data/interface.go
rest/historical_test_data_routes.go
rest/historical_test_data_routes_test.go
rest/model/historical_test_data.go
rest/model/historical_test_data_test.go
rest/service.go

JIRA: https://jira.mongodb.org/browse/EVG-13447
This is the final PR for this ticket. It actually adds the REST route to fetch historical test data using the aggregation merged with a previous PR.

EVG-13447: Implement historical test routes in cedar

---

perf/ftdc_rollups.go

JIRA: https://jira.mongodb.org/browse/EVG-13812
Limits ftdc processing size limit to 4GB or less.

EVG-13812: Add size limit to ftdc files we process

---

model/buildlogger.go
model/buildlogger_test.go
model/config.go
units/crons.go
units/migrate_task_logs.go

JIRA: Change task level logs to use tags instead of process_name
This is temporary code for the task log migration.

EVG-13831: Change task level logs to use tags instead of process_name

---

model/buildlogger.go
model/buildlogger_test.go

JIRA: https://jira.mongodb.org/browse/EVG-13831
Turns out the index was not being used as we expected, unfortunately `$ne` and `$nin` are not selective and thus indexes cannot be used with them. So as the number of docs with `agent_log`, `task_log`, and `system_log` in the `info.tags` array increased, the time the query took to filter out those docs increased drastically. 
This code changes the update to remove the `info.proc` field as way to mark that doc as processed.

EVG-13831: Remove proc_name in migration

---

rest/data/interface.go

JIRA: https://jira.mongodb.org/browse/EVG-13761
Was updating the wiki and realized some of the buildlogger documentation in `rest/data/interface.go` was outdated.

EVG-13761: Update some buildlogger documentation

---

perf/ftdc_rollups.go
perf/ftdc_rollups_test.go
perf/rollup_factory.go
units/find_outdated_rollups.go

JIRA: https://jira.mongodb.org/browse/EVG-13536
The backfill job for outdated perf rollup jobs is already limited to update results created within the past 90 days. For a change that affects every single perf result (like adding a new rollup) this can be overwhelming for the amboy queue, creating duplicate jobs and backing it up. This change reverts the revert of a commit I made recently to add a new perf rollup and adds limits a the backfill job to 1000 results per job (which runs every hour) to avoid overwhelming the queue again. The database has about ~240,000 perf results that were created in the past 90 days. Not all of these results have ftdc data and thus will not need to be updated. But even all ~240,000 results needed to be updated, this would only take about 10 days. I chose …

EVG-13536: Limit outdated rollup job to 1000 results per job

---

model/test_results_iterator.go
model/test_results_iterator_test.go

JIRA: https://jira.mongodb.org/browse/EVG-13419
In effort to create a new rest route to fetch test results by display name we will need to iterator over multiple `TestResultsIterator`s, so I created a new `multiTestResultsIterator` for convenience.

EVG-13419: Create a mutli test results iterator

---

model/test_results.go
model/test_results_test.go
rest/data/interface.go
rest/data/test_results.go
rest/data/test_results_test.go
rest/test_results_routes.go
rest/test_results_routes_test.go

JIRA: https://jira.mongodb.org/browse/EVG-13419
This changes the `TestResults.FindByTaskID` method to `FindTestResults` and enables searching by `DisplayTaskName`.

EVG-13419: New Find methods for test results

---

model/log_iterator.go
model/test_results_iterator.go
model/test_results_iterator_test.go

JIRA: https://jira.mongodb.org/browse/EVG-14242
The test results rest routes have long latencies (~5s) due to the fact that they must iterator through a pail bucket and download each file individually. To speed up the process I added some parallelization.

EVG-14242: Parallelize downloading test results

---

model/indexes.go
model/perf.go
model/perf_test.go
model/time_series_update.go
rest/data/perf.go
rest/perf_routes.go

JIRA: https://jira.mongodb.org/browse/EVG-14066
The bug in EVG-14066 is caused by missing indexes. I did an audit of the `perf_results` collection's indexes and cleaned them up. I also cleaned up the code about and changed the perf with children route to use `$isSetSubset` instead of `$eq` when comparing tags.

EVG-14066: Update indexes and clean up some perf code

---

model/buildlogger_test.go

JIRA: https://jira.mongodb.org/browse/EVG-14223
This took me hours to figure out and ended up being really stupid: occasionally the pail file is overwritten by the second call to append. The pail key is a string of the unix timestamp in milliseconds of `time.Now` and since the appends are called sequentially, this would sometimes result in the same millisecond precision unix timestamp and the first log file would get overwritten.

EVG-14223: Fix flaky buildlogger append test

---

makefile

JIRA: https://jira.mongodb.org/browse/EVG-14234
* Always recompile when `build/cedar` is the target or dependency. This is more correct than just assuming we don't have to compile if the binary exists, even if it's outdated (what it does now).
* As an alternative, we could do what Evergreen does, which is run `find` to locate all the Go source files, then use those as Make dependencies for compilation. However, this is inefficient (slower than just letting Go recompile using its build cache) and also runs unconditionally (even for targets that are unrelated to compiling).
* Make the `clean` target simpler.

EVG-14234: always compile with go build

---

model/perf.go
model/perf_test.go
rest/buildlogger_routes.go
rest/data/interface.go
rest/data/perf.go
rest/data/perf_test.go
rest/parse.go
rest/perf_routes.go
rest/perf_routes_test.go

JIRA: https://jira.mongodb.org/browse/EVG-14175
* Remove interval from perf version/task ID routes.
* Use YYYY-MM-DD timestamp format for perf task name route.
* Use options struct for perf data connector and consolidate find methods.
* I'll update the perf/buildlogger REST docs once this is merged.

EVG-14175: clean up perf routes

---

units/historical_test_data.go

JIRA: https://jira.mongodb.org/browse/EVG-14420
Set the unique job ID. I could have just used `j.Info.ID()`, but I thought it would be more human-friendly to have a searchable job ID rather than a hash.

EVG-14420: set job ID for historical test data job

---

rest/model/historical_test_data.go

JIRA: https://jira.mongodb.org/browse/EVG-14523
This is for backwards compatibility. The field names in the API struct should be the same as Evergreen's.

EVG-14523: Update cedar historical test data API struct to match evergreen's

---

model/indexes.go

JIRA: https://jira.mongodb.org/browse/EVG-14612
When fetching perf results by `task_id` or `version` we allow filtering by tags and sort by the `created_at` date. So far it hasn't been an issue for fetching by `task_id` since there typically are not many results in a single task id / execution run and nobody was using the `version` route until now.

EVG-14612: Add indexes in the perf_results collection

---

model/test_results.go
model/test_results_iterator.go
model/test_results_test.go
rest/data/test_results.go
rest/data/test_results_test.go
rest/test_results_routes_test.go
rpc/internal/test_results_service_test.go

JIRA: https://jira.mongodb.org/browse/EVG-14672
This stores test results as a single file in the respective s3 bucket location for the results. There really is no need to store results individually since they are tiny and the bottleneck ends up being network calls to s3.
There will be a follow up ticket to create a migration job for existing results stored the old way.

EVG-14672: store test results more efficiently

---

model/perf.go
model/perf_test.go

JIRA: https://jira.mongodb.org/browse/EVG-14848

EVG-14848: Store perf arguments in sorted order in the db

---

model/test_results.go
model/test_results_test.go
rpc/internal/test_results_service.go

JIRA: https://jira.mongodb.org/browse/EVG-15254
This is to optimize fetching of a sample of the failing tests for a given task, used by the UI for hover pop-ups.

EVG-15254: Add first 10 failing tests to test results DB doc

---

model/test_results.go
model/test_results_test.go
rest/data/interface.go
rest/data/test_results.go
rest/data/test_results_test.go
rest/model/test_results.go
rest/service.go
rest/test_results_routes.go
rest/test_results_routes_test.go

JIRA: https://jira.mongodb.org/browse/EVG-15303
- Add new function to fetch test results stats for a single task id or aggregate test results for tasks in a display task id.
- Add new rest data connector function to fetch test results stats
- Add new route
- Refactor some tests in the rest and rest/data package
- Rename `NumFailed` to `FailCount` for consistency

EVG-15303: Add new test results stats route

---

rest/buildlogger_routes.go

JIRA: https://jira.mongodb.org/browse/EVG-15354
This occurs when a test log was not able to close out so the `completed_at` field is zero, for example, when a resmoke test timeouts.

EVG-15354: Make sure time range is valid when fetching grouped logs

---

model/time_series_update.go
rpc/internal/perf_service.go
rpc/internal/perf_service_test.go
units/time_series_update.go

JIRA: https://jira.mongodb.org/browse/EVG-15386
- This also fixes the periodic aggregation and creates a time-series-update job in `CreateMetricSeries` when there are rollups.

EVG-15386: Add scopes to time-series-update job 

---

units/time_series_update.go

[EVG-15454](https://jira.mongodb.org/browse/EVG-15454)
Rounding timestamps down to the nearest hour is too aggressive for the `time-series-update` job, especially now that we have scopes in place. This is rate limiting updates to SPS causing a backlog of unprocessed perf results every hour.

EVG-15454: Use time.Now() for time-series-update IDs.

---

model/time_series_update.go

[EVG-15454](https://jira.mongodb.org/browse/EVG-15454)
The `PerformanceArguments` is just a map that implements the `bson.Marshaler` interface to ensure alphabetical order of keys since order matters for BSON objects.

EVG-15454: Use PerformanceArguments type in PerformanceSeriesID

---

rest/model/perf.go
rest/perf_routes.go
rest/perf_routes_test.go
rest/service.go

This sends a shortened message iff perf results exists, otherwise returning a 404 error.

EVG-14837: Create cedar route to determine if perf data exists for a task

---

model/perf.go
model/perf_test.go

JIRA: https://jira.mongodb.org/browse/EVG-15514
This is causing a bug where we try to look up perf results with no args but instead pass in `info.args: {}` to the query.

EVG-15514: Marshal the PerformanceArguments type to the BSON null value when empty

---

environment.go

JIRA: https://jira.mongodb.org/browse/EVG-15612
The atlas cluster is currently an m200 tier, which has a max connection limit of 128k. Since certain loads can be write-heavy, we should increase the max connection pool size. The app servers each have a ulimit of 256k so they can also safely handle this. I picked 1000 kind of arbitrarily (the default is 100), but I think its enough, we can always increase if needed.

EVG-15612: set mongo driver max pool size to 1000

---

rest/buildlogger_routes.go
rest/log_error.go
rest/perf_routes.go
rest/system_metrics_routes.go
rest/test_results_routes.go

https://jira.mongodb.org/browse/EVG-14303
Wrap all the rest/route level `grip.Error`s in a function that lowers the log level for 404s.
I figured we still need to return the 404s (like Kim's https://github.com/evergreen-ci/cedar/pull/410#discussion_r747814999) but it's not really an _error_ so the `Info` level makes more sense.

EVG-14303 adjust log level conditionally

---

.github/dependabot.yml
makefile

Jira: https://jira.mongodb.org/browse/EVG-15449
This enables Dependabot automatic upgrades for Go modules. Dependabot will periodically check all dependencies in `go.mod` for newer stable versions (it doesn't upgrade unversioned repos) and bump them if there's a newer one available. This initial merge will also trigger Dependabot to do an immediate check for new dependency versions, so merging this may trigger other Dependabot PRs to be opened.
* Check for updates monthly to make it minimally annoying.
* Increase the open PR limit from the default of 5. It's preferable to get all the available upgrades ASAP rather than have Dependabot incrementally give us a subset of all the available updates.
* I set myself as the reviewer on all the Dependabot PRs and merge the ones that appear every …

EVG-15449: use Dependabot for automated dependency upgrades

---

go.mod
go.sum

Jira: https://jira.mongodb.org/browse/EVG-15734

EVG-15734: Bump github.com/mongodb/jasper from v0.0.0-20211118154831-ee0b5744e192 to v0.0.0-20211213143437-1d373fd6f2c6

---

model/perf.go
model/perf_test.go
model/time_series_update.go
perf/time_series_updater.go
rest/data/perf.go
rest/perf_routes.go
rpc/internal/perf_service.go
units/ftdc_rollups.go
units/time_series_update.go
units/time_series_update_periodic.go
units/time_series_update_periodic_test.go
units/time_series_update_test.go

JIRA: https://jira.mongodb.org/browse/EVG-16072
The SPS is now using the analytics node to run aggregations that fetch performance result time series data so we only need to send the time series ID rather than running the aggregation in amboy jobs and sending all of the time series data.

EVG-16037: Only send time series IDs to signal process service

---

cmd/convert-bson-to-parquet/convert-bson-to-parquet.go
go.mod
go.sum
model/config.go
model/test_results.go
model/test_results_test.go
rest/data/test_results_test.go
rest/test_results_routes_test.go
rpc/internal/test_results_service_test.go

JIRA: https://jira.mongodb.org/browse/EVG-16137, https://jira.mongodb.org/browse/EVG-16136
Store test results in both BSON and Parquet, when fetching results pull both Parquet and BSON and compare.

EVG-16137, EVG-16136: Store test results in Parquet and fetch and compare

---

model/batch_job_controller.go
model/batch_job_controller_test.go
model/migration_stats.go
model/test_results.go
model/test_results_test.go
units/bson_to_parquet_backfill.go
units/bson_to_parquet_backfill_test.go
units/ftdc_rollups_test.go
units/units_test.go

JIRA: https://jira.mongodb.org/browse/EVG-16138
- Create a new Amboy job that migrates BSON test result data from our S3 bucket to Parquet format and writes it to the Presto bucket.
- Add a new `BatchJobController` model to enable controlling batch jobs without requiring app restarts/deploys.
- Add a new `MigrationStats` model, used as a sub-document in the `TestResults` docs in the temporary backfill collection for keeping track of the batch job stats and enabling versioning (in case we need to rerun the migration).
- Clean up some test files in the `units` package.
Testing
- I added unit tests, and we will test in this staging. The job itself will not be run yet in production.

EVG-16138: Production-Ready BSON to Parquet Backfill 

---

model/config_flags.go
units/crons.go

JIRA: https://jira.mongodb.org/browse/EVG-16138
- Add a new operations flag to the config to disable the job if needed.
- Run the job on each app server's local Amboy queue every minute.

EVG-16138: Run BSON to Parquet Test Results Backfill Job

---

model/config_flags.go
model/test_results.go
model/test_results_test.go

JIRA: https://jira.mongodb.org/browse/EVG-16137
- Add fields that are necessary for the test stats API.
- Update tests and make testing more robust.
- Add a new operations flag `DisableParquetTestResults` to disable writing Parquet test results to the Presto bucket.

EVG-16137: Add TaskName and RequestType fields to TestResults Parquet struct

---

model/historical_test_data.go

JIRA: https://jira.mongodb.org/browse/EVG-16140
We are moving all test stats to a new (unsharded) collection called `presto_historical_test_data`. The application should read from that collection when processing test stats requests.

EVG-16140: Read test stats from new collection

---

model/test_results.go
model/test_results_test.go
rest/data/test_results_test.go
rest/test_results_routes_test.go

find test results will now do an aggregation for execution tasks and return previous executions as well 
example 
display_task {
et1: execution 0
et2: execution 0, 1
}
findTestResults(execution = 1) -> returns et1 exec0, et2 exec 1
findTestResults(execution = empty) -> returns et1 exec0, et2 exec 1 (latest for all exec tasks)
findTestResults(execution = 0) -> returns et1 exec0, et2 exec 0
This changes the return value for execution tasks so I'm not sure if this will break things on evergreen?

EVG-16988 Update FindTestResults to handle new execution task logic

---

benchmarks/log_iterator_benchmarks.go
benchmarks/timber_benchmarks.go
model/log_iterator_test.go
model/test_results_test.go

[EVG-16225](https://jira.mongodb.org/browse/EVG-16225)
These are the tasks/tests that are somewhat consistently broken on the waterfall:
- [TestMergeLogIterator](https://github.com/evergreen-ci/cedar/blob/1e54beabc6b94e499b4322c875144a6bad55835f/model/log_iterator_test.go#L220) It seems like the issue is that the multiple log iterators have identical chunk keys when all the logs are created in the same millisecond (which is pretty likely) and if pail writes the second iterator's logs with the same key they get [overwritten](https://github.com/evergreen-ci/pail/blob/6bd16e3e14f02deb552e6a42a93c5a170f66ffbb/local.go#L123) ("truncated"). Giving each iterator its own backing tempdir solves this.
- [Lint for getLogIteratorBenchmarkSuite](https://github.com/evergreen-ci/cedar/blob/49eaa32561fb10 …

EVG-16225 fix flakey tests

---

rpc/service.go

In an attempt to speed up deploys, let's reduce the time we give for a graceful shutdown to just one minute.

EVG-16531: Reduce graceful shutdown to 1 minute

---

.github/dependabot.yml

Jira: https://jira.mongodb.org/browse/EVG-18423
Change the Dependabot PR reviewers to team review. I've historically maintained Dependabot upgrades for PLT repos. The way it works is that, once per month on the first day of the month, Dependabot will search all our dependencies in our `go.mod` that use Go semantic versioning. It would then open PRs for those modules that have an updated version available, which are then manually reviewed and merged. I used a script to manage quickly merging those that passed all CI tests.
Once this is merged, I'm also going to apply this change to all the other Go repos (aside from evergreen-ci/evergreen, which isn't using Dependabot yet) without review, since these settings are basically the same across all our repos.
Checking and merging Dependabot PRs …

EVG-18423: update Dependabot reviewers

---

model/test_results.go
model/test_results_test.go
rest/data/interface.go
rest/data/test_results.go
rest/data/test_results_test.go
rest/service.go
rest/test_results_routes.go
rest/test_results_routes_test.go

JIRA: https://jira.mongodb.org/browse/EVG-18798
- Add three new routes to fetch test results, test result stats, and failed test sample by multiple (task ID, execution) pairs
- Fix pagination bug that was caused by not sorting test results that were downloaded in parallel (the order needs to be consistent for pagination to work properly)
- Write new tests for both the routes and the bug fix

EVG-18798: Add multi-task test results rest routes

---

model/test_results.go
model/test_results_test.go
rest/data/interface.go
rest/data/test_results.go
rest/data/test_results_test.go
rest/service.go
rest/test_results_routes.go
rest/test_results_routes_test.go

JIRA: https://jira.mongodb.org/browse/EVG-18798
- Remove old test results fetching routes
- Clean up any other TODOs
Tested that the fetching routes work as expected and the legacy + Spruce UIs test fetching works in staging.

EVG-18798: clean up TODOs and remove old routes

---

perf/ftdc_rollups.go
perf/ftdc_rollups_test.go
perf/rollup_factory.go
units/find_outdated_rollups.go

We weren't including the duration of the first operation in the totalWallTime calculation, which leads DurationTotal to be wrong in the trend charts / rollups.

EVG-18181: Fix how we calculate totalWallTime.

---

model/test_results.go
model/test_results_test.go
rest/data/interface.go
rest/data/test_results.go
rest/test_results_routes.go

JIRA: https://jira.mongodb.org/browse/EVG-14306
This code change enables multiple sort criteria on test results. I kept the API backwards compatible for the switchover.

EVG-14306: Enable multi sort on test results

---

model/test_results.go

JIRA: https://jira.mongodb.org/browse/EVG-14306
Small clean up based on feedback from https://github.com/evergreen-ci/evergreen/pull/6402.

EVG-14306: Use map[string]bool instead of map[string]int when detecting duplicate test sort criteria

---

rpc/internal/perf_service.go
rpc/internal/perf_service_test.go
units/time_series_update.go

JIRA: https://jira.mongodb.org/browse/EVG-19750
- Only enqueue the time-series-update job once for a performance result upon the final call to `CloseMetrics`
- Add the `measurements` to the scope for each job
- Add more better testing to the perf results RPC service code

EVG-19750: fix time-series-update job race condition when there is both user-submitted rollups and FTDC rollups

---

model/test_results.go
model/test_results_test.go
rest/data/interface.go
rest/data/test_results.go

JIRA: https://jira.mongodb.org/browse/EVG-20455
We need to enable not only regex matches on display test names but also on the unique test names to support fetching test logs with the graphql resolver [EVG-20443](https://jira.mongodb.org/browse/EVG-20443). This adds a new option to "exclude display names" when matching on the test name regex, the default behavior will continue to favor matching on display test name—the changes are backwards compatible.

EVG-20455: enable the exclusion of display test names from the test name regex filter

---

model/time_series_update.go

[DEVPROD-1950](https://jira.mongodb.org/browse/DEVPROD-1950)
- Update `GetUnanalyzedPerformanceSeries` to look only check for unanalyzed perf results from the past 7 days
- Update `MarkPerformanceResultsAsAnalyzed` to only update results for mainline perf results from the most recent 7 days

DEVPROD-1950: only check for and mark analyzed perf results for the most recent 7 days

---

Dockerfile

This is just adding the base Dockerfile for Cedar. It has a default cmd that will spin up a very small instance of Cedar - this will be overridden in actual production deployments to have a more appropriately sized worker number.

DEVPROD-4495: Dockerize Cedar

---

evergreen.yaml

[DEVPROD-3139](https://jira.mongodb.org/browse/DEVPROD-3139)
Use mongo 7.0 in tests to make sure we're all clear to go to 7.0.
Upgrade mongosh while we're here.

DEVPROD-3139 mongo 6.0 -> 7.0

---

README.rst

Some of the cedar tests require a replicaset to be available locally in order to run `make cedar test`.
This PR updates the documentation to reflect that.

DEVPROD-7132 Document the requirements to run the cedar tests locally

---

model/indexes.go

This PR adds a new index to the list of required cedar indexes.
I've tested this by adding pushing this to staging, where no indexes exist. This results in the following warning in the log:
```
[cedar] 2024/05/21 14:19:30 [p=error]: missing expected DB indexes: 
...
expected index '[{info.override_info.override_mainline 1}]' is missing from collection 'perf_results'
...
```
With the index, the above line disappears.
Before we deploy this change, I'll manually create the index in production as well. Once the change goes in, I'll monitor that the newly deployed version does not print the above warning.

DEVPROD-7253 Add a new index to the cedar DB for the overrides field

---

model/indexes.go

This PR adds the new index required for the overrides pipeline to the indexes.go file.
I've verified on staging that this matches the index we are planning to create.

DEVPROD-7257 Add index to support new pipeline
