rest/model/model.go, rest/model/perf.go, rest/model/perf_test.go, rest/model/string.go, rest/model/string_test.go, rest/model/time.go, rest/model/time_test.go
Package build, implementation completed for `PerformanceResult` struct. Skipped implementation for `Export`.
=> MAKE-508: build restmodels package

model/config.go, model/config_flags.go, model/config_test.go, model/model_test.go, operations/config.go, operations/service.go, operations/setup.go, units/build_cost_report.go
this builds on top of #27 and includes them
=> MAKE-563: add feature flag support

model/perf.go
really small thing that was bothering me
=> created_ts -> created_at

model/buildlogger.go, model/buildlogger_test.go, model/log_iterator.go, model/log_iterator_test.go, util/time.go, util/time_range.go
This is a WIP because I have not written tests. Would like to first go over and get approval for design.
=> MAKE-777: Implement downloader

perf/change_point_detector.go
It looks like the retrying logic should pretty much handle everything. I've set max retries to 10 since I don't think things will get better after 10 failures and we should examine that case more closely, and removed 500 from the recoverable errors since this corresponds to an unhandled exception from our API.
=> MAKE-1050: Add error handling to signal processing detector client

model/change_point_detection.go, model/perf_data.go, units/recalculate_change_points_periodic_test.go
=> MAKE-1130: Fix periodic change point job

glide.lock, units/ftdc_rollups.go, vendor/github.com/mongodb/amboy/queue/remote_base.go, vendor/github.com/mongodb/amboy/queue/remote_unordered.go
this is just https://github.com/mongodb/amboy/pull/137 with a minor tweak. 
making a PR to run these tests
=> MAKE-1123: fix amboy dispatching

rest/routes.go
JIRA: https://jira.mongodb.org/browse/MAKE-1170
=> MAKE-1170: return if username is missing

rest/data/perf.go, rpc/internal/perf_service.go, units/ftdc_rollups.go, units/recalculate_change_points_periodic.go
https://jira.mongodb.org/browse/MAKE-1155
=> MAKE-1155: Use new putunique API in cedar/amboy

.golangci.yml, cmd/run-linter/run-linter.go, cost/aws_spot_price.go, cost/spend_test.go, depgraph/graph_map.go, environment.go, makefile, model/buildlogger.go, model/buildlogger_test.go, model/cost_report.go, model/perf.go, model/perf_data_test.go, perf/ftdc_rollups_test.go, rest/data/perf.go, rpc/internal/perf_service.go, units/recalculate_change_points_periodic.go
JIRA: https://jira.mongodb.org/browse/MAKE-1149
=> MAKE-1149: use golangci-lint

rest/service.go
JIRA: https://jira.mongodb.org/browse/MAKE-1173
=> MAKE-1173: remove GET route for login

operations/before.go, operations/client.go, operations/flags.go, rest/client.go, rest/routes.go, rest/service.go
JIRA: https://jira.mongodb.org/browse/EVG-12442
* Fix bugs that made the REST client unusable from the CLI.
* Fix misspellings.
=> EVG-12442: fix various bugs in REST client

rest/routes.go
We're going to stop using checkPayloadCreds soon, but it seems like it shouldn't return internal server error for any failure related to authenticating the user.
=> EVG-9204: clean up checkPayloadCreds

.gitignore, rpc/service.go
JIRA: https://jira.mongodb.org/browse/EVG-12721
* Drive-by fix for gitignore pattern.
=> EVG-12721: attach system metrics gRPC service

cmd/run-linter/run-linter.go, makefile, rpc/internal/system_metrics_service.go
JIRA: https://jira.mongodb.org/browse/EVG-12721
* I don't see any obvious causes of problems when testing system metrics, so I want to debug what requests are made to the gRPC service.
* Also drive-by improvement to makefile's linting.
=> EVG-12721: add debug logs for system metrics

rest/data/interface.go, rest/data/system_metrics.go, rest/data/system_metrics_test.go, rest/system_metrics_routes.go, rest/system_metrics_routes_test.go
JIRA: https://jira.mongodb.org/browse/EVG-12820
This adds pagination for system metrics to the rest package.
=> EVG-12820: Add pagination for system metrics rest routes

rpc/internal/test_results_service.go
JIRA: https://jira.mongodb.org/browse/EVG-8914
=> EVG-8914: enqueue historical test data job when new test result arrives

model/indexes.go, model/indexes_test.go, operations/service.go, rest/data/test_results.go
JIRA: https://jira.mongodb.org/browse/EVG-13135
* Add function to check that indexes exist (ignoring extra options such as "unique"/"sparse").
* Log error when indexes are missing. I'll add a splunk alert for missing indexes.
=> EVG-13135: log error if required indexes are missing

rest/routes.go
JIRA: https://jira.mongodb.org/browse/EVG-13637
=> EVG-13637: Remove amboy info and stats from status endpoint

operations/worker.go, vendor/github.com/mongodb/amboy/pool/helpers.go, vendor/github.com/mongodb/amboy/queue/driver_mongo.go
JIRA: https://jira.mongodb.org/browse/EVG-14082
Since I can't revendor amboy yet without breaking things, I increased the level of important logs in the current vendored version.
=> EVG-14082: Increase debug logging to info for important logs

rest/data/perf.go, rest/perf_routes.go
JIRA: https://jira.mongodb.org/browse/EVG-14066
I am debugging for this ticket and realized our perf routes have really poor error messages. Once this gets approved I will deploy to see what is going on.
=> EVG-14066: Improve perf rest route error messages.

operations/service.go, rest/routes.go
JIRA: https://jira.mongodb.org/browse/EVG-14335
This should be backwards compatible.
=> EVG-14335: add usr to domains

rpc/internal/buildlogger_service_test.go
JIRA: https://jira.mongodb.org/browse/EVG-14319
=> EVG-14319: Fix failing rpc-internal test

model/perf.go, model/perf_test.go, rest/data/perf.go, rest/data/perf_test.go
JIRA: https://jira.mongodb.org/browse/EVG-14380
=> EVG-14380: Do not filter by mainline when getting perf results by version

glide.lock, operations/admin.go, rest/routes.go, vendor/github.com/evergreen-ci/certdepot/.golangci.yml, vendor/github.com/evergreen-ci/certdepot/bootstrap.go, vendor/github.com/evergreen-ci/certdepot/bootstrap_test.go, vendor/github.com/evergreen-ci/certdepot/cert.go, vendor/github.com/evergreen-ci/certdepot/cert_test.go, vendor/github.com/evergreen-ci/certdepot/cmd/run-linter/run-linter.go, vendor/github.com/evergreen-ci/certdepot/db_test.go, vendor/github.com/evergreen-ci/certdepot/depot_test.go, vendor/github.com/evergreen-ci/certdepot/evergreen.yaml, vendor/github.com/evergreen-ci/certdepot/file.go, vendor/github.com/evergreen-ci/certdepot/interface.go, vendor/github.com/evergreen-ci/certdepot/makefile, vendor/github.com/evergreen-ci/certdepot/mgo_depot.go, vendor/github.com/evergreen-ci/certdepot/mongodb_depot.go, vendor/github.com/evergreen-ci/certdepot/mongodb_options.go, vendor/github.com/evergreen-ci/certdepot/pkix.go, vendor/github.com/evergreen-ci/certdepot/superset.go
JIRA: https://jira.mongodb.org/browse/EVG-14382
=> EVG-14382: revendor certdepot

units/historical_test_data.go
JIRA: https://jira.mongodb.org/browse/EVG-14420
=> EVG-14420: register historical test data job

rpc/internal/test_results_service.go
JIRA: https://jira.mongodb.org/browse/EVG-14438
=> EVG-14438: disable historical test data job

model/indexes.go, rpc/internal/test_results_service.go, rpc/internal/test_results_service_test.go
JIRA: https://jira.mongodb.org/browse/EVG-14440
=> EVG-14440: Add historical test data indexes and use display test name when available

model/test_results.go
JIRA: https://jira.mongodb.org/browse/EVG-14514
=> EVG-14514: Parallelize uploading of test results to s3

rest/historical_test_data_routes.go, rest/model/historical_test_data.go
JIRA: https://jira.mongodb.org/browse/EVG-14629
=> EVG-14629: Fix historical test data pagination date format

rest/buildlogger_routes.go, rest/buildlogger_routes_test.go, rest/data/buildlogger.go, rest/data/buildlogger_test.go, rest/data/interface.go, rest/service.go
JIRA: https://jira.mongodb.org/browse/EVG-14657
=> EVG-14657: Add cedar REST endpoint for fetching all logs of a group id

rpc/service.go
JIRA: https://jira.mongodb.org/browse/EVG-14775
=> EVG-14775: Force close gRPC service if cannot gracefully stop

model/perf.go, model/perf_test.go, rest/data/interface.go, rest/data/perf.go, rest/data/perf_test.go, rest/perf_routes.go, rest/perf_routes_test.go
JIRA: https://jira.mongodb.org/browse/EVG-14612
This rest route can return 10s of thousands of results, we should paginate.
=> EVG-14612: Paginate `/perf/version/{version}` route

model/test_results.go
JIRA: https://jira.mongodb.org/browse/EVG-14968
=> EVG-14968: parallelize test results downloading

rest/service.go
JIRA: https://jira.mongodb.org/browse/EVG-14657
I set the route to version 0 instead of version 1.
=> EVG-14657: Update version for REST route

glide.lock, vendor/github.com/evergreen-ci/gimlet/app_merge.go, vendor/github.com/evergreen-ci/gimlet/okta/okta.go, vendor/github.com/evergreen-ci/gimlet/okta/okta_test.go, vendor/github.com/evergreen-ci/gimlet/parsing.go, vendor/github.com/evergreen-ci/gimlet/parsing_test.go
[EVG-14923](https://jira.mongodb.org/browse/EVG-14923)
=> EVG-14923 Revendor gimlet

model/test_results.go, model/test_results_test.go, rest/data/interface.go, rest/data/test_results.go, rest/data/test_results_test.go, rest/service.go, rest/test_results_routes.go, rest/test_results_routes_test.go
JIRA: https://jira.mongodb.org/browse/EVG-15254
=> EVG-15254: Add REST route to fetch failing tests sample

model/perf_data.go
JIRA: https://jira.mongodb.org/browse/EVG-15269
=> EVG-15269: Ensure that the update result is not nil before checking it

rest/service.go, rest/test_results_routes.go, rest/test_results_routes_test.go
JIRA: https://jira.mongodb.org/browse/EVG-15299
I tested that this works with display tasks and regular tasks in staging.
=> EVG-15299: simply test results rest route

.gitignore, rpc/internal/perf_service.go, rpc/internal/perf_service_test.go
[EVG-15255](https://jira.mongodb.org/browse/EVG-15255)
If the report contains rollups with no artifacts we need to enqueue a time series update right away.
=> EVG-15255 new update time series job

model/test_results.go, model/test_results_test.go, rest/buildlogger_routes.go
JIRA: https://jira.mongodb.org/browse/EVG-15263
Will update the REST route to support filtering, sorting, and pagination in a subsequent PR.
=> EVG-15354: Add test results filtering, sorting, and pagination capabilities

model/time_series_update.go, perf/time_series_updater.go, units/crons.go, units/time_series_update_periodic.go
JIRA: https://jira.mongodb.org/browse/EVG-15538
=> EVG-15538: Limit time series update aggregation and run periodic job more often

model/perf.go, model/perf_test.go, rpc/internal/perf_service.go, units/find_outdated_rollups.go, units/find_outdated_rollups_test.go
Implement https://github.com/evergreen-ci/cedar/pull/380#discussion_r701953667
=> EVG-15372 add FTDC format check

rest/data/interface.go, rest/data/test_results.go
https://jira.mongodb.org/browse/EVG-15729
Add json tags to match the tags in https://github.com/evergreen-ci/timber/pull/90.
=> EVG-15729 add tags and rename a field

stats_cache.go
JIRA: https://jira.mongodb.org/browse/EVG-15972
=> EVG-15972: Fix concurrent map access in stats cache

.golangci.yml, model/buildlogger.go, model/system_metrics_test.go, model/users_test.go, perf/rollup_factory.go, rest/buildlogger_routes_test.go, rest/client_test.go, rest/model/perf_test.go, rest/perf_routes_test.go, rest/system_metrics_routes_test.go
Jira: https://jira.mongodb.org/browse/EVG-15952
=> EVG-15952: use gofmt linter

config.go, environment.go, go.mod, go.sum
Jira: https://jira.mongodb.org/browse/EVG-15931
Upgrade Amboy and update the refactored fields.
I tested that the remote queue still works as expected in staging.
=> EVG-15931: upgrade Amboy

go.mod, go.sum, model/config.go, model/pail_storage.go, model/test_results.go
JIRA: https://jira.mongodb.org/browse/EVG-16463
Since the AWS client session will be assuming a role to access to the Presto bucket, we need to pipe through the ARN of the role.
=> EVG-16463: Pipe through Presto bucket IAM Role ARN

go.mod, go.sum
[EVG-17961](https://jira.mongodb.org/browse/EVG-17961)
It would be nice to get the query params in the Splunk logs.
=> EVG-17961 update gimlet

rest/test_results_routes.go, rest/test_results_routes_test.go
The struct tag should be `filter` not `filters`.
=> EVG-18798: fix JSON struct tag for test results payload

units/crons.go
Stop running the find-outdated-rollups job. The Performance Build Baron Team has asked us not to run this job to update historical statistics because it might cause issues with historical build failures.
=> EVG-19321: Disable find-outdated-rollups cron.

rpc/internal/perf_service.go
Too much spam with the original message
=> DEVPROD-7558: Update FTDC log message

cmd/cedar/cedar.go, operations/calculate_rollup.go, operations/flags.go
I tested this against a few different tasks on the waterfall and this seemed to be getting all of the metrics we are expecting.
=> DEVPROD-7729: Add CLI to Cedar to turn FTDC file into JSON

operations/setup.go
Comment out to see if this will help the apps start up.
=> DEVPROD-18670: Comment out Slack logging setup
